// Code generated by hertz generator.

package synapse

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	basicuser1 "github.com/xh-polaris/synapse/biz/api/model/basicuser"
)

// BasicUserRegister .
// @router /basic_user/register [POST]
func BasicUserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req basicuser1.BasicUserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basicuser1.BasicUserRegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// BasicUserLogin .
// @router /basic_user/login [POST]
func BasicUserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req basicuser1.BasicUserLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(basicuser1.BasicUserLoginResp)

	c.JSON(consts.StatusOK, resp)
}
