// Code generated by hertz generator.

package synapse

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	system1 "github.com/xh-polaris/synapse/biz/api/model/system"
)

// SendVerifyCode .
// @router /system/send_verify_code [POST]
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system1.SendVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(system1.SendVerifyCodeResp)

	c.JSON(consts.StatusOK, resp)
}
