// Code generated by hertz generator.

package synapse

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basic_userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}
